### ISSUE TITLE
Cert formatting

### ISSUE THREAD

**Issue by s2t2** [18F/identity-dashboard#150]
As someone responsible for collecting client sp information from the dashboard and adding it to the identity-idp's configuration, when I copy the cert text from the browser and paste it into a text editor, I notice the cert appears on a single line rather than on multiple lines.

It is possible to access the multi-line cert using the browser's inspect element tool, but it would be a better user experience to stay in the front-end of the browser.

Perhaps wrapping the text in a`<code>` block, or some other light change might work.

**Comment by blacktm** [comment]
Yea, that's been totally annoying 😫 I've got a PR in the works that updates the view on that and other pages when content should really be a code snippet.

**Comment by blacktm** [comment]
Done in #154 ([see line](https://github.com/18F/identity-dashboard/pull/154/files#diff-c03bcbec5e4a266fd581261e84500bffR49)).
