### ISSUE TITLE
Out of date USWDS banner text

### ISSUE THREAD

**Issue by konklone** [18F/identity-dashboard#177]
The dashboard is currently using the inaccurate out-of-date USWDS banner text:

<img width="1129" alt="screen shot 2018-08-12 at 1 36 03 pm" src="https://user-images.githubusercontent.com/4592/44004703-bb80f110-9e34-11e8-9c28-5045b161f1a4.png">

It'd be worth updating to the current banner. For an example, see https://designsystem.digital.gov -

<img width="1107" alt="screen shot 2018-08-12 at 1 36 50 pm" src="https://user-images.githubusercontent.com/4592/44004707-ce562cec-9e34-11e8-8eef-a9ac0b4834f5.png">

**Comment by mitchellhenke** [comment]
Looks like this is good now 🙂 

![image](https://user-images.githubusercontent.com/1430443/94852906-30299d00-03f0-11eb-8e76-388ea0b29531.png)
