### ISSUE TITLE
create rake task for admin account creation

### ISSUE THREAD

**Issue by bleachbyte** [18F/identity-dashboard#262]
Currently, creating an admin account in the dashboard must be done specifically on the Rails console, via:
```
[1] pry(main)> User.count
   (0.7ms)  SELECT COUNT(*) FROM "users"
=> 0
[2] pry(main)> bleachbyte = User.new
=> #<User id: nil, uuid: nil, email: nil, first_name: nil, last_name: nil, created_at: nil, updated_at: nil, admin: false, group_id: nil>
[3] pry(main)> bleachbyte.email = "jonathan.pirro@gsa.gov"
=> "jonathan.pirro@gsa.gov"
[4] pry(main)> bleachbyte.admin = true
=> true
[5] pry(main)> bleachbyte.first_name = "Jonathan"
=> "Jonathan"
[6] pry(main)> bleachbyte.last_name = "Pirro"
=> "Pirro"
[7] pry(main)> bleachbyte.save
   (0.7ms)  BEGIN
  User Exists (0.9ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "jonathan.pirro@gsa.gov"], ["LIMIT", 1]]
  SQL (0.9ms)  INSERT INTO "users" ("email", "first_name", "last_name", "created_at", "updated_at", "admin") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["email", "jonathan.pirro@gsa.gov"], ["first_name", "Jonathan"], ["last_name", "Pirro"], ["created_at", "2019-10-28 21:59:55.159042"], ["updated_at", "2019-10-28 21:59:55.159042"], ["admin", "t"]]
   (1.1ms)  COMMIT
=> true
```

This isn't a _super_ common task, but it would be more convenient to have as a `rake` task, rather than directly requiring a login to the Rails console. (Side note: This is also a self-starter project for me to get my feet wet building `rake` tasks.)

**Comment by solipet** [comment]
Note that creating an admin user in development/test Rails envs happens as part of seeding the db: https://github.com/18F/identity-dashboard/pull/241

**Comment by bleachbyte** [comment]
The only issue with that is the fact that the admin@gsa.gov address can't be accessed on a sandbox environment, as it doesn't use Mailcatcher and therefore you can't perform verification.

Created #263 for this.

**Comment by bleachbyte** [comment]
Merged; this is completed.
